/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './_services/me.service';
import * as import9 from '../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import10 from '../../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from '@angular/core/src/linker/view_container';
import * as import13 from '@angular/router/src/router';
import * as import14 from '@angular/router/src/router_state';
import * as import15 from '@angular/common/src/location/location_strategy';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/router/src/directives/router_link';
import * as import18 from '@angular/router/src/directives/router_link_active';
import * as import19 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import20 from '../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import21 from '@angular/core/src/change_detection/change_detection_util';
import * as import22 from '@angular/core/src/linker/template_ref';
import * as import23 from '@angular/router/src/router_outlet_map';
import * as import24 from '@angular/core/src/linker/component_factory_resolver';
import * as import25 from '@angular/common/src/directives/ng_if';
import * as import26 from '@angular/router/src/directives/router_outlet';
export class Wrapper_AppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AppComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.AppComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AppComponent>;
  _AppComponent_0_3:Wrapper_AppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent_Host0,renderType_AppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppComponent0(this.viewUtils,this,0,this._el_0);
    this._AppComponent_0_3 = new Wrapper_AppComponent(this.injectorGet(import8.MeService,this.parentIndex));
    this.compView_0.create(this._AppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppComponentNgFactory:import7.ComponentFactory<import0.AppComponent> = new import7.ComponentFactory<import0.AppComponent>('app',View_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = ([] as any[]);
class View_AppComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _el_3:any;
  _RouterLinkWithHref_3_3:import9.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_3_4:import10.Wrapper_RouterLinkActive;
  _query_RouterLink_3_0:import11.QueryList<any>;
  _query_RouterLinkWithHref_3_1:import11.QueryList<any>;
  _text_4:any;
  _text_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_AppComponent1,renderType_AppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'ul',new import3.InlineArray2(2,'class','nav navbar-nav navbar-right pull-right'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_2,'a',new import3.InlineArray4(4,'routerLink','/admin','routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_3_3 = new import9.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import13.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import14.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import15.LocationStrategy,this.parentView.parentIndex));
    this._RouterLinkActive_3_4 = new import10.Wrapper_RouterLinkActive(this.parentView.parentView.injectorGet(import13.Router,this.parentView.parentIndex),new import16.ElementRef(this._el_3),this.renderer,this.parentView.ref);
    this._query_RouterLink_3_0 = new import11.QueryList<any>();
    this._query_RouterLinkWithHref_3_1 = new import11.QueryList<any>();
    this._text_4 = this.renderer.createText(this._el_3,'+ Admin',(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_3,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_3));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._text_5
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.RouterLinkWithHref) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._RouterLinkWithHref_3_3.context; }
    if (((token === import18.RouterLinkActive) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._RouterLinkActive_3_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3_0_0:any = '/admin';
    this._RouterLinkWithHref_3_3.check_routerLink(currVal_3_0_0,throwOnChange,false);
    this._RouterLinkWithHref_3_3.ngDoCheck(this,this._el_3,throwOnChange);
    const currVal_3_1_0:any = 'active';
    this._RouterLinkActive_3_4.check_routerLinkActive(currVal_3_1_0,throwOnChange,false);
    this._RouterLinkActive_3_4.ngDoCheck(this,this._el_3,throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_3_0.dirty) {
        this._query_RouterLink_3_0.reset(([] as any[]));
        this._RouterLinkActive_3_4.context.links = this._query_RouterLink_3_0;
        this._query_RouterLink_3_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_3_1.dirty) {
        this._query_RouterLinkWithHref_3_1.reset([this._RouterLinkWithHref_3_3.context]);
        this._RouterLinkActive_3_4.context.linksWithHrefs = this._query_RouterLinkWithHref_3_1;
        this._query_RouterLinkWithHref_3_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_3_4.context.ngAfterContentInit(); }
    }
    this._RouterLinkWithHref_3_3.checkHost(this,this,this._el_3,throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_3_3.ngOnDestroy();
    this._RouterLinkActive_3_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_3(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_3_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
var renderType_AppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_AppComponent,{});
export class View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _RouterLinkWithHref_7_3:import9.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_7_4:import10.Wrapper_RouterLinkActive;
  _query_RouterLink_7_0:import11.QueryList<any>;
  _query_RouterLinkWithHref_7_1:import11.QueryList<any>;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _vc_15:import12.ViewContainer;
  _TemplateRef_15_5:any;
  _NgIf_15_6:import19.Wrapper_NgIf;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  /*private*/ _vc_22:import12.ViewContainer;
  _RouterOutlet_22_5:import20.Wrapper_RouterOutlet;
  _text_23:any;
  /*private*/ _expr_33:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent0,renderType_AppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_33 = import21.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'nav',new import3.InlineArray2(2,'class','navbar navbar-default'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container-fluid col-lg-8 col-lg-offset-2 col-md-12'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_4 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','navbar-header'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'a',new import3.InlineArray8(6,'class','navbar-brand navbar-left','routerLink','/','routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_7_3 = new import9.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import13.Router,this.parentIndex),this.parentView.injectorGet(import14.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import15.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_7_4 = new import10.Wrapper_RouterLinkActive(this.parentView.injectorGet(import13.Router,this.parentIndex),new import16.ElementRef(this._el_7),this.renderer,this.ref);
    this._query_RouterLink_7_0 = new import11.QueryList<any>();
    this._query_RouterLinkWithHref_7_1 = new import11.QueryList<any>();
    this._text_8 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._text_9 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_7,'span',new import3.InlineArray2(2,'class','pull-left'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'# show all',(null as any));
    this._text_12 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._text_13 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._vc_15 = new import12.ViewContainer(15,2,this,this._anchor_15);
    this._TemplateRef_15_5 = new import22.TemplateRef_(this,15,this._anchor_15);
    this._NgIf_15_6 = new import19.Wrapper_NgIf(this._vc_15.vcRef,this._TemplateRef_15_5);
    this._text_16 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_2,'small',new import3.InlineArray2(2,'class','navbar-text navbar-right paddingRight30'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'',(null as any));
    this._text_19 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_20 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_21 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,parentRenderNode,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_22 = new import12.ViewContainer(22,(null as any),this,this._el_22);
    this._RouterOutlet_22_5 = new import20.Wrapper_RouterOutlet(this.parentView.injectorGet(import23.RouterOutletMap,this.parentIndex),this._vc_22.vcRef,this.parentView.injectorGet(import24.ComponentFactoryResolver,this.parentIndex),(null as any));
    this._text_23 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_7,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_7));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.RouterLinkWithHref) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._RouterLinkWithHref_7_3.context; }
    if (((token === import18.RouterLinkActive) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._RouterLinkActive_7_4.context; }
    if (((token === import22.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import25.NgIf) && (15 === requestNodeIndex))) { return this._NgIf_15_6.context; }
    if (((token === import26.RouterOutlet) && (22 === requestNodeIndex))) { return this._RouterOutlet_22_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_7_0_0:any = '/';
    this._RouterLinkWithHref_7_3.check_routerLink(currVal_7_0_0,throwOnChange,false);
    this._RouterLinkWithHref_7_3.ngDoCheck(this,this._el_7,throwOnChange);
    const currVal_7_1_0:any = 'active';
    this._RouterLinkActive_7_4.check_routerLinkActive(currVal_7_1_0,throwOnChange,false);
    this._RouterLinkActive_7_4.ngDoCheck(this,this._el_7,throwOnChange);
    const currVal_15_0_0:any = ((this.context.me == null)? (null as any): this.context.me.is_admin);
    this._NgIf_15_6.check_ngIf(currVal_15_0_0,throwOnChange,false);
    this._NgIf_15_6.ngDoCheck(this,this._anchor_15,throwOnChange);
    this._RouterOutlet_22_5.ngDoCheck(this,this._el_22,throwOnChange);
    this._vc_15.detectChangesInNestedViews(throwOnChange);
    this._vc_22.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_7_0.dirty) {
        this._query_RouterLink_7_0.reset(([] as any[]));
        this._RouterLinkActive_7_4.context.links = this._query_RouterLink_7_0;
        this._query_RouterLink_7_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_7_1.dirty) {
        this._query_RouterLinkWithHref_7_1.reset([this._RouterLinkWithHref_7_3.context]);
        this._RouterLinkActive_7_4.context.linksWithHrefs = this._query_RouterLinkWithHref_7_1;
        this._query_RouterLinkWithHref_7_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_7_4.context.ngAfterContentInit(); }
    }
    this._RouterLinkWithHref_7_3.checkHost(this,this,this._el_7,throwOnChange);
    const currVal_33:any = import3.inlineInterpolate(1,'Signed in as @',((this.context.me == null)? (null as any): this.context.me.id),'');
    if (import3.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setText(this._text_18,currVal_33);
      this._expr_33 = currVal_33;
    }
  }
  destroyInternal():void {
    this._vc_15.destroyNestedViews();
    this._vc_22.destroyNestedViews();
    this._RouterLinkWithHref_7_3.ngOnDestroy();
    this._RouterLinkActive_7_4.ngOnDestroy();
    this._RouterOutlet_22_5.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 15)) { return new View_AppComponent1(this.viewUtils,this,15,this._anchor_15,this._vc_15); }
    return (null as any);
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_7_3.handleEvent(eventName,$event) && result);
    return result;
  }
}