/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './main.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../_services/hstrigger.service';
import * as import9 from '../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import10 from '../../../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from 'angular2-moment/time-ago.pipe';
import * as import13 from '@angular/core/src/linker/view_container';
import * as import14 from '@angular/core/src/change_detection/change_detection_util';
import * as import15 from '@angular/router/src/router';
import * as import16 from '@angular/router/src/router_state';
import * as import17 from '@angular/common/src/location/location_strategy';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/core/src/zone/ng_zone';
import * as import20 from '@angular/router/src/directives/router_link';
import * as import21 from '@angular/router/src/directives/router_link_active';
import * as import22 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import23 from '@angular/core/src/linker/template_ref';
import * as import24 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import25 from '@angular/common/src/directives/ng_for';
import * as import26 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import27 from '../_pipes/truncate.pipe';
import * as import28 from 'angular2-moment/date-format.pipe';
import * as import29 from '@angular/common/src/directives/ng_if';
export class Wrapper_MainComponent {
  /*private*/ _eventHandler:Function;
  context:import0.MainComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.MainComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_MainComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_MainComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.MainComponent>;
  _MainComponent_0_3:Wrapper_MainComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MainComponent_Host0,renderType_MainComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'main-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_MainComponent0(this.viewUtils,this,0,this._el_0);
    this._MainComponent_0_3 = new Wrapper_MainComponent(this.injectorGet(import8.HSTriggerService,this.parentIndex));
    this.compView_0.create(this._MainComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._MainComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MainComponent) && (0 === requestNodeIndex))) { return this._MainComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MainComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const MainComponentNgFactory:import7.ComponentFactory<import0.MainComponent> = new import7.ComponentFactory<import0.MainComponent>('main-component',View_MainComponent_Host0,import0.MainComponent);
const styles_MainComponent:any[] = ([] as any[]);
class View_MainComponent2 extends import1.AppView<any> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  _el_5:any;
  _RouterLinkWithHref_5_3:import9.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_5_4:import10.Wrapper_RouterLinkActive;
  _query_RouterLink_5_0:import11.QueryList<any>;
  _query_RouterLinkWithHref_5_1:import11.QueryList<any>;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  /*private*/ _expr_23:any;
  _pipe_truncate_0_0:any;
  /*private*/ _expr_25:any;
  _pipe_amDateFormat_1_0:any;
  _pipe_amTimeAgo_0:import12.TimeAgoPipe;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_MainComponent2,renderType_MainComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_23 = import14.UNINITIALIZED;
    this._expr_25 = import14.UNINITIALIZED;
    this._expr_28 = import14.UNINITIALIZED;
    this._expr_29 = import14.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._text_0 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,(null as any),'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n                    ',(null as any));
    this._text_3 = this.renderer.createText(this._el_1,'\n                    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_1,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_4,'a',new import3.InlineArray2(2,'routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_5_3 = new import9.Wrapper_RouterLinkWithHref(this.parentView.parentView.parentView.injectorGet(import15.Router,this.parentView.parentView.parentIndex),this.parentView.parentView.parentView.injectorGet(import16.ActivatedRoute,this.parentView.parentView.parentIndex),this.parentView.parentView.parentView.injectorGet(import17.LocationStrategy,this.parentView.parentView.parentIndex));
    this._RouterLinkActive_5_4 = new import10.Wrapper_RouterLinkActive(this.parentView.parentView.parentView.injectorGet(import15.Router,this.parentView.parentView.parentIndex),new import18.ElementRef(this._el_5),this.renderer,this.parentView.parentView.ref);
    this._query_RouterLink_5_0 = new import11.QueryList<any>();
    this._query_RouterLinkWithHref_5_1 = new import11.QueryList<any>();
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_1,'\n                    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_1,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_1,'\n                    ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_1,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_1,'\n                    ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_1,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'',(null as any));
    this._text_16 = this.renderer.createText(this._el_1,'\n                ',(null as any));
    this._text_17 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n            ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_5,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_5));
    this._pipe_truncate_0_0 = import3.pureProxy3((<View_MainComponent0>this.parentView.parentView)._pipe_truncate_0.transform.bind((<View_MainComponent0>this.parentView.parentView)._pipe_truncate_0));
    this._pipe_amDateFormat_1_0 = import3.pureProxy2((<View_MainComponent0>this.parentView.parentView)._pipe_amDateFormat_1.transform.bind((<View_MainComponent0>this.parentView.parentView)._pipe_amDateFormat_1));
    this._pipe_amTimeAgo_0 = new import12.TimeAgoPipe(this.parentView.parentView.ref,this.parentView.injectorGet(import19.NgZone,this.parentIndex));
    this.init(this._text_18,((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.RouterLinkWithHref) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._RouterLinkWithHref_5_3.context; }
    if (((token === import21.RouterLinkActive) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._RouterLinkActive_5_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import14.ValueUnwrapper();
    const currVal_5_0_0:any = import3.inlineInterpolate(1,'/gpview/',this.context.$implicit.gp_ref,'');
    this._RouterLinkWithHref_5_3.check_routerLink(currVal_5_0_0,throwOnChange,false);
    this._RouterLinkWithHref_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    const currVal_5_1_0:any = 'active';
    this._RouterLinkActive_5_4.check_routerLinkActive(currVal_5_1_0,throwOnChange,false);
    this._RouterLinkActive_5_4.ngDoCheck(this,this._el_5,throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_5_0.dirty) {
        this._query_RouterLink_5_0.reset(([] as any[]));
        this._RouterLinkActive_5_4.context.links = this._query_RouterLink_5_0;
        this._query_RouterLink_5_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_5_1.dirty) {
        this._query_RouterLinkWithHref_5_1.reset([this._RouterLinkWithHref_5_3.context]);
        this._RouterLinkActive_5_4.context.linksWithHrefs = this._query_RouterLinkWithHref_5_1;
        this._query_RouterLinkWithHref_5_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_5_4.context.ngAfterContentInit(); }
    }
    this._RouterLinkWithHref_5_3.checkHost(this,this,this._el_5,throwOnChange);
    valUnwrapper.reset();
    const currVal_23:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_truncate_0_0,(<View_MainComponent0>this.parentView.parentView)._pipe_truncate_0.transform)(((this.context.$implicit.first_flow == null)? (null as any): this.context.$implicit.first_flow.title),50,'...')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_23,currVal_23))) {
      this.renderer.setText(this._text_6,currVal_23);
      this._expr_23 = currVal_23;
    }
    valUnwrapper.reset();
    const currVal_25:any = import3.inlineInterpolate(2,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_amDateFormat_1_0,(<View_MainComponent0>this.parentView.parentView)._pipe_amDateFormat_1.transform)(this.context.$implicit.first_dt,'DD MMM YYYY HH:mm')),' (',valUnwrapper.unwrap(this._pipe_amTimeAgo_0.transform(this.context.$implicit.first_dt)),')');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_25,currVal_25))) {
      this.renderer.setText(this._text_9,currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_28:any = import3.inlineInterpolate(1,'',this.parentView.parentView.context.toText('status',((this.context.$implicit.first_flow == null)? (null as any): this.context.$implicit.first_flow.status)),'');
    if (import3.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setText(this._text_12,currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = import3.inlineInterpolate(1,'',this.parentView.parentView.context.toText('priority',((this.context.$implicit.first_flow == null)? (null as any): this.context.$implicit.first_flow.priority)),'');
    if (import3.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setText(this._text_15,currVal_29);
      this._expr_29 = currVal_29;
    }
  }
  destroyInternal():void {
    this._RouterLinkWithHref_5_3.ngOnDestroy();
    this._RouterLinkActive_5_4.ngOnDestroy();
    this._pipe_amTimeAgo_0.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._text_0,ctx);
    cb(this._el_1,ctx);
    cb(this._text_17,ctx);
    cb(this._text_18,ctx);
  }
  handleEvent_5(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_5_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_MainComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import13.ViewContainer;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import22.Wrapper_NgFor;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_MainComponent1,renderType_MainComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import13.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import23.TemplateRef_(this,2,this._anchor_2);
    this._NgFor_2_6 = new import22.Wrapper_NgFor(this._vc_2.vcRef,this._TemplateRef_2_5,this.parentView.parentView.injectorGet(import24.IterableDiffers,this.parentView.parentIndex),this.parentView.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import25.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.context.groups;
    this._NgFor_2_6.check_ngForOf(currVal_2_0_0,throwOnChange,false);
    this._NgFor_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_MainComponent2(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
}
var renderType_MainComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_MainComponent,{});
export class View_MainComponent0 extends import1.AppView<import0.MainComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _vc_23:import13.ViewContainer;
  _TemplateRef_23_5:any;
  _NgIf_23_6:import26.Wrapper_NgIf;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _pipe_truncate_0:import27.TruncatePipe;
  _pipe_amDateFormat_1:import28.DateFormatPipe;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MainComponent0,renderType_MainComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container col-lg-8 col-lg-offset-2 col-md-12 '),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'table',new import3.InlineArray2(2,'class','table table-striped table-hover nobordertop form-group'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'thead',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._text_8 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_6,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'Approval Title',(null as any));
    this._text_11 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_6,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Started',(null as any));
    this._text_14 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_6,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'Status',(null as any));
    this._text_17 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_6,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'Priority',(null as any));
    this._text_20 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_21 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_22 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._vc_23 = new import13.ViewContainer(23,2,this,this._anchor_23);
    this._TemplateRef_23_5 = new import23.TemplateRef_(this,23,this._anchor_23);
    this._NgIf_23_6 = new import26.Wrapper_NgIf(this._vc_23.vcRef,this._TemplateRef_23_5);
    this._text_24 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_25 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_26 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._pipe_truncate_0 = new import27.TruncatePipe();
    this._pipe_amDateFormat_1 = new import28.DateFormatPipe();
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._anchor_23,
      this._text_24,
      this._text_25,
      this._text_26
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import29.NgIf) && (23 === requestNodeIndex))) { return this._NgIf_23_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_23_0_0:any = this.context.groups;
    this._NgIf_23_6.check_ngIf(currVal_23_0_0,throwOnChange,false);
    this._NgIf_23_6.ngDoCheck(this,this._anchor_23,throwOnChange);
    this._vc_23.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_23.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 23)) { return new View_MainComponent1(this.viewUtils,this,23,this._anchor_23,this._vc_23); }
    return (null as any);
  }
}