/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/http/src/http_module';
import * as import6 from '@angular/router/src/router_module';
import * as import7 from './app.routes';
import * as import8 from '@angular/common/src/localization';
import * as import9 from '@angular/core/src/application_init';
import * as import10 from '@angular/core/src/testability/testability';
import * as import11 from '@angular/core/src/application_ref';
import * as import12 from '@angular/core/src/linker/compiler';
import * as import13 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import14 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import15 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import16 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import17 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import18 from '@angular/core/src/animation/animation_queue';
import * as import19 from '@angular/core/src/linker/view_utils';
import * as import20 from '@angular/platform-browser/src/browser/title';
import * as import21 from '@angular/http/src/backends/browser_xhr';
import * as import22 from '@angular/http/src/base_response_options';
import * as import23 from '@angular/http/src/backends/xhr_backend';
import * as import24 from '@angular/http/src/base_request_options';
import * as import25 from '@angular/common/src/location/location';
import * as import26 from '@angular/router/src/url_tree';
import * as import27 from '@angular/router/src/router_outlet_map';
import * as import28 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import29 from '@angular/router/src/router_preloader';
import * as import30 from '@angular/core/src/di/injector';
import * as import31 from './app.component.ngfactory';
import * as import32 from '@angular/core/src/i18n/tokens';
import * as import33 from '@angular/core/src/application_tokens';
import * as import34 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import35 from '@angular/platform-browser/src/dom/events/key_events';
import * as import36 from '@angular/core/src/zone/ng_zone';
import * as import37 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import38 from '@angular/common/src/location/platform_location';
import * as import39 from '@angular/common/src/location/location_strategy';
import * as import40 from '@angular/router/src/url_handling_strategy';
import * as import41 from '@angular/router/src/route_reuse_strategy';
import * as import42 from '@angular/router/src/router';
import * as import43 from '@angular/core/src/console';
import * as import44 from '@angular/core/src/error_handler';
import * as import45 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import46 from '@angular/platform-browser/src/dom/animation_driver';
import * as import47 from '@angular/core/src/render/api';
import * as import48 from '@angular/core/src/security';
import * as import49 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import50 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import51 from '@angular/http/src/interfaces';
import * as import52 from '@angular/http/src/http';
import * as import53 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import54 from '@angular/router/src/router_config_loader';
import * as import55 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _HttpModule_3:import5.HttpModule;
  _ROUTER_FORROOT_GUARD_4:any;
  _RouterModule_5:import6.RouterModule;
  _AppRoutesModule_6:import7.AppRoutesModule;
  _AppModule_7:import1.AppModule;
  __LOCALE_ID_8:any;
  __NgLocalization_9:import8.NgLocaleLocalization;
  _ErrorHandler_10:any;
  _RouterInitializer_11:import6.RouterInitializer;
  _APP_INITIALIZER_12:any[];
  _ApplicationInitStatus_13:import9.ApplicationInitStatus;
  _Testability_14:import10.Testability;
  _ApplicationRef__15:import11.ApplicationRef_;
  __ApplicationRef_16:any;
  __Compiler_17:import12.Compiler;
  __APP_ID_18:any;
  __DOCUMENT_19:any;
  __HAMMER_GESTURE_CONFIG_20:import13.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_21:any[];
  __EventManager_22:import14.EventManager;
  _DomSharedStylesHost_23:import15.DomSharedStylesHost;
  __AnimationDriver_24:any;
  __DomRootRenderer_25:import16.DomRootRenderer_;
  __NgProbeToken_26:any[];
  __RootRenderer_27:any;
  __DomSanitizer_28:import17.DomSanitizerImpl;
  __Sanitizer_29:any;
  __AnimationQueue_30:import18.AnimationQueue;
  __ViewUtils_31:import19.ViewUtils;
  __IterableDiffers_32:any;
  __KeyValueDiffers_33:any;
  __SharedStylesHost_34:any;
  __Title_35:import20.Title;
  __BrowserXhr_36:import21.BrowserXhr;
  __ResponseOptions_37:import22.BaseResponseOptions;
  __XSRFStrategy_38:any;
  __XHRBackend_39:import23.XHRBackend;
  __RequestOptions_40:import24.BaseRequestOptions;
  __Http_41:any;
  __ROUTER_CONFIGURATION_42:any;
  __LocationStrategy_43:any;
  __Location_44:import25.Location;
  __UrlSerializer_45:import26.DefaultUrlSerializer;
  __RouterOutletMap_46:import27.RouterOutletMap;
  __NgModuleFactoryLoader_47:import28.SystemJsNgModuleLoader;
  __ROUTES_48:any[];
  __Router_49:any;
  __ActivatedRoute_50:any;
  _NoPreloading_51:import29.NoPreloading;
  _PreloadingStrategy_52:any;
  _RouterPreloader_53:import29.RouterPreloader;
  __PreloadAllModules_54:import29.PreloadAllModules;
  __ROUTER_INITIALIZER_55:any;
  __APP_BOOTSTRAP_LISTENER_56:any[];
  constructor(parent:import30.Injector) {
    super(parent,[import31.AppComponentNgFactory],[import31.AppComponentNgFactory]);
  }
  get _LOCALE_ID_8():any {
    if ((this.__LOCALE_ID_8 == null)) { (this.__LOCALE_ID_8 = import3._localeFactory(this.parent.get(import32.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_8;
  }
  get _NgLocalization_9():import8.NgLocaleLocalization {
    if ((this.__NgLocalization_9 == null)) { (this.__NgLocalization_9 = new import8.NgLocaleLocalization(this._LOCALE_ID_8)); }
    return this.__NgLocalization_9;
  }
  get _ApplicationRef_16():any {
    if ((this.__ApplicationRef_16 == null)) { (this.__ApplicationRef_16 = this._ApplicationRef__15); }
    return this.__ApplicationRef_16;
  }
  get _Compiler_17():import12.Compiler {
    if ((this.__Compiler_17 == null)) { (this.__Compiler_17 = new import12.Compiler()); }
    return this.__Compiler_17;
  }
  get _APP_ID_18():any {
    if ((this.__APP_ID_18 == null)) { (this.__APP_ID_18 = import33._appIdRandomProviderFactory()); }
    return this.__APP_ID_18;
  }
  get _DOCUMENT_19():any {
    if ((this.__DOCUMENT_19 == null)) { (this.__DOCUMENT_19 = import4._document()); }
    return this.__DOCUMENT_19;
  }
  get _HAMMER_GESTURE_CONFIG_20():import13.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_20 == null)) { (this.__HAMMER_GESTURE_CONFIG_20 = new import13.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_20;
  }
  get _EVENT_MANAGER_PLUGINS_21():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_21 == null)) { (this.__EVENT_MANAGER_PLUGINS_21 = [
      new import34.DomEventsPlugin(),
      new import35.KeyEventsPlugin(),
      new import13.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_20)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_21;
  }
  get _EventManager_22():import14.EventManager {
    if ((this.__EventManager_22 == null)) { (this.__EventManager_22 = new import14.EventManager(this._EVENT_MANAGER_PLUGINS_21,this.parent.get(import36.NgZone))); }
    return this.__EventManager_22;
  }
  get _AnimationDriver_24():any {
    if ((this.__AnimationDriver_24 == null)) { (this.__AnimationDriver_24 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_24;
  }
  get _DomRootRenderer_25():import16.DomRootRenderer_ {
    if ((this.__DomRootRenderer_25 == null)) { (this.__DomRootRenderer_25 = new import16.DomRootRenderer_(this._DOCUMENT_19,this._EventManager_22,this._DomSharedStylesHost_23,this._AnimationDriver_24,this._APP_ID_18)); }
    return this.__DomRootRenderer_25;
  }
  get _NgProbeToken_26():any[] {
    if ((this.__NgProbeToken_26 == null)) { (this.__NgProbeToken_26 = [import6.routerNgProbeToken()]); }
    return this.__NgProbeToken_26;
  }
  get _RootRenderer_27():any {
    if ((this.__RootRenderer_27 == null)) { (this.__RootRenderer_27 = import37._createConditionalRootRenderer(this._DomRootRenderer_25,this.parent.get(import37.NgProbeToken,(null as any)),this._NgProbeToken_26)); }
    return this.__RootRenderer_27;
  }
  get _DomSanitizer_28():import17.DomSanitizerImpl {
    if ((this.__DomSanitizer_28 == null)) { (this.__DomSanitizer_28 = new import17.DomSanitizerImpl()); }
    return this.__DomSanitizer_28;
  }
  get _Sanitizer_29():any {
    if ((this.__Sanitizer_29 == null)) { (this.__Sanitizer_29 = this._DomSanitizer_28); }
    return this.__Sanitizer_29;
  }
  get _AnimationQueue_30():import18.AnimationQueue {
    if ((this.__AnimationQueue_30 == null)) { (this.__AnimationQueue_30 = new import18.AnimationQueue(this.parent.get(import36.NgZone))); }
    return this.__AnimationQueue_30;
  }
  get _ViewUtils_31():import19.ViewUtils {
    if ((this.__ViewUtils_31 == null)) { (this.__ViewUtils_31 = new import19.ViewUtils(this._RootRenderer_27,this._Sanitizer_29,this._AnimationQueue_30)); }
    return this.__ViewUtils_31;
  }
  get _IterableDiffers_32():any {
    if ((this.__IterableDiffers_32 == null)) { (this.__IterableDiffers_32 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_32;
  }
  get _KeyValueDiffers_33():any {
    if ((this.__KeyValueDiffers_33 == null)) { (this.__KeyValueDiffers_33 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_33;
  }
  get _SharedStylesHost_34():any {
    if ((this.__SharedStylesHost_34 == null)) { (this.__SharedStylesHost_34 = this._DomSharedStylesHost_23); }
    return this.__SharedStylesHost_34;
  }
  get _Title_35():import20.Title {
    if ((this.__Title_35 == null)) { (this.__Title_35 = new import20.Title()); }
    return this.__Title_35;
  }
  get _BrowserXhr_36():import21.BrowserXhr {
    if ((this.__BrowserXhr_36 == null)) { (this.__BrowserXhr_36 = new import21.BrowserXhr()); }
    return this.__BrowserXhr_36;
  }
  get _ResponseOptions_37():import22.BaseResponseOptions {
    if ((this.__ResponseOptions_37 == null)) { (this.__ResponseOptions_37 = new import22.BaseResponseOptions()); }
    return this.__ResponseOptions_37;
  }
  get _XSRFStrategy_38():any {
    if ((this.__XSRFStrategy_38 == null)) { (this.__XSRFStrategy_38 = import5._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_38;
  }
  get _XHRBackend_39():import23.XHRBackend {
    if ((this.__XHRBackend_39 == null)) { (this.__XHRBackend_39 = new import23.XHRBackend(this._BrowserXhr_36,this._ResponseOptions_37,this._XSRFStrategy_38)); }
    return this.__XHRBackend_39;
  }
  get _RequestOptions_40():import24.BaseRequestOptions {
    if ((this.__RequestOptions_40 == null)) { (this.__RequestOptions_40 = new import24.BaseRequestOptions()); }
    return this.__RequestOptions_40;
  }
  get _Http_41():any {
    if ((this.__Http_41 == null)) { (this.__Http_41 = import5.httpFactory(this._XHRBackend_39,this._RequestOptions_40)); }
    return this.__Http_41;
  }
  get _ROUTER_CONFIGURATION_42():any {
    if ((this.__ROUTER_CONFIGURATION_42 == null)) { (this.__ROUTER_CONFIGURATION_42 = {}); }
    return this.__ROUTER_CONFIGURATION_42;
  }
  get _LocationStrategy_43():any {
    if ((this.__LocationStrategy_43 == null)) { (this.__LocationStrategy_43 = import6.provideLocationStrategy(this.parent.get(import38.PlatformLocation),this.parent.get(import39.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_42)); }
    return this.__LocationStrategy_43;
  }
  get _Location_44():import25.Location {
    if ((this.__Location_44 == null)) { (this.__Location_44 = new import25.Location(this._LocationStrategy_43)); }
    return this.__Location_44;
  }
  get _UrlSerializer_45():import26.DefaultUrlSerializer {
    if ((this.__UrlSerializer_45 == null)) { (this.__UrlSerializer_45 = new import26.DefaultUrlSerializer()); }
    return this.__UrlSerializer_45;
  }
  get _RouterOutletMap_46():import27.RouterOutletMap {
    if ((this.__RouterOutletMap_46 == null)) { (this.__RouterOutletMap_46 = new import27.RouterOutletMap()); }
    return this.__RouterOutletMap_46;
  }
  get _NgModuleFactoryLoader_47():import28.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_47 == null)) { (this.__NgModuleFactoryLoader_47 = new import28.SystemJsNgModuleLoader(this._Compiler_17,this.parent.get(import28.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_47;
  }
  get _ROUTES_48():any[] {
      if ((this.__ROUTES_48 == null)) { (this.__ROUTES_48 = [[
        {
          path: '',
          loadChildren: './+main/main.module#MainModule'
        }
        ,
        {
          path: '**',
          redirectTo: '/',
          pathMatch: 'full'
        }

      ]
    ]); }
    return this.__ROUTES_48;
  }
  get _Router_49():any {
    if ((this.__Router_49 == null)) { (this.__Router_49 = import6.setupRouter(this._ApplicationRef_16,this._UrlSerializer_45,this._RouterOutletMap_46,this._Location_44,this,this._NgModuleFactoryLoader_47,this._Compiler_17,this._ROUTES_48,this._ROUTER_CONFIGURATION_42,this.parent.get(import40.UrlHandlingStrategy,(null as any)),this.parent.get(import41.RouteReuseStrategy,(null as any)))); }
    return this.__Router_49;
  }
  get _ActivatedRoute_50():any {
    if ((this.__ActivatedRoute_50 == null)) { (this.__ActivatedRoute_50 = import6.rootRoute(this._Router_49)); }
    return this.__ActivatedRoute_50;
  }
  get _PreloadAllModules_54():import29.PreloadAllModules {
    if ((this.__PreloadAllModules_54 == null)) { (this.__PreloadAllModules_54 = new import29.PreloadAllModules()); }
    return this.__PreloadAllModules_54;
  }
  get _ROUTER_INITIALIZER_55():any {
    if ((this.__ROUTER_INITIALIZER_55 == null)) { (this.__ROUTER_INITIALIZER_55 = import6.getBootstrapListener(this._RouterInitializer_11)); }
    return this.__ROUTER_INITIALIZER_55;
  }
  get _APP_BOOTSTRAP_LISTENER_56():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_56 == null)) { (this.__APP_BOOTSTRAP_LISTENER_56 = [this._ROUTER_INITIALIZER_55]); }
    return this.__APP_BOOTSTRAP_LISTENER_56;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._HttpModule_3 = new import5.HttpModule();
    this._ROUTER_FORROOT_GUARD_4 = import6.provideForRootGuard(this.parent.get(import42.Router,(null as any)));
    this._RouterModule_5 = new import6.RouterModule(this._ROUTER_FORROOT_GUARD_4);
    this._AppRoutesModule_6 = new import7.AppRoutesModule();
    this._AppModule_7 = new import1.AppModule();
    this._ErrorHandler_10 = import4.errorHandler();
    this._RouterInitializer_11 = new import6.RouterInitializer(this);
    this._APP_INITIALIZER_12 = [import6.getAppInitializer(this._RouterInitializer_11)];
    this._ApplicationInitStatus_13 = new import9.ApplicationInitStatus(this._APP_INITIALIZER_12);
    this._Testability_14 = new import10.Testability(this.parent.get(import36.NgZone));
    this._ApplicationRef__15 = new import11.ApplicationRef_(this.parent.get(import36.NgZone),this.parent.get(import43.Console),this,this._ErrorHandler_10,this,this._ApplicationInitStatus_13,this.parent.get(import10.TestabilityRegistry,(null as any)),this._Testability_14);
    this._DomSharedStylesHost_23 = new import15.DomSharedStylesHost(this._DOCUMENT_19);
    this._NoPreloading_51 = new import29.NoPreloading();
    this._PreloadingStrategy_52 = this._NoPreloading_51;
    this._RouterPreloader_53 = new import29.RouterPreloader(this._Router_49,this._NgModuleFactoryLoader_47,this._Compiler_17,this,this._PreloadingStrategy_52);
    return this._AppModule_7;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.HttpModule)) { return this._HttpModule_3; }
    if ((token === import6.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_4; }
    if ((token === import6.RouterModule)) { return this._RouterModule_5; }
    if ((token === import7.AppRoutesModule)) { return this._AppRoutesModule_6; }
    if ((token === import1.AppModule)) { return this._AppModule_7; }
    if ((token === import32.LOCALE_ID)) { return this._LOCALE_ID_8; }
    if ((token === import8.NgLocalization)) { return this._NgLocalization_9; }
    if ((token === import44.ErrorHandler)) { return this._ErrorHandler_10; }
    if ((token === import6.RouterInitializer)) { return this._RouterInitializer_11; }
    if ((token === import9.APP_INITIALIZER)) { return this._APP_INITIALIZER_12; }
    if ((token === import9.ApplicationInitStatus)) { return this._ApplicationInitStatus_13; }
    if ((token === import10.Testability)) { return this._Testability_14; }
    if ((token === import11.ApplicationRef_)) { return this._ApplicationRef__15; }
    if ((token === import11.ApplicationRef)) { return this._ApplicationRef_16; }
    if ((token === import12.Compiler)) { return this._Compiler_17; }
    if ((token === import33.APP_ID)) { return this._APP_ID_18; }
    if ((token === import45.DOCUMENT)) { return this._DOCUMENT_19; }
    if ((token === import13.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_20; }
    if ((token === import14.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_21; }
    if ((token === import14.EventManager)) { return this._EventManager_22; }
    if ((token === import15.DomSharedStylesHost)) { return this._DomSharedStylesHost_23; }
    if ((token === import46.AnimationDriver)) { return this._AnimationDriver_24; }
    if ((token === import16.DomRootRenderer)) { return this._DomRootRenderer_25; }
    if ((token === import11.NgProbeToken)) { return this._NgProbeToken_26; }
    if ((token === import47.RootRenderer)) { return this._RootRenderer_27; }
    if ((token === import17.DomSanitizer)) { return this._DomSanitizer_28; }
    if ((token === import48.Sanitizer)) { return this._Sanitizer_29; }
    if ((token === import18.AnimationQueue)) { return this._AnimationQueue_30; }
    if ((token === import19.ViewUtils)) { return this._ViewUtils_31; }
    if ((token === import49.IterableDiffers)) { return this._IterableDiffers_32; }
    if ((token === import50.KeyValueDiffers)) { return this._KeyValueDiffers_33; }
    if ((token === import15.SharedStylesHost)) { return this._SharedStylesHost_34; }
    if ((token === import20.Title)) { return this._Title_35; }
    if ((token === import21.BrowserXhr)) { return this._BrowserXhr_36; }
    if ((token === import22.ResponseOptions)) { return this._ResponseOptions_37; }
    if ((token === import51.XSRFStrategy)) { return this._XSRFStrategy_38; }
    if ((token === import23.XHRBackend)) { return this._XHRBackend_39; }
    if ((token === import24.RequestOptions)) { return this._RequestOptions_40; }
    if ((token === import52.Http)) { return this._Http_41; }
    if ((token === import6.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_42; }
    if ((token === import39.LocationStrategy)) { return this._LocationStrategy_43; }
    if ((token === import25.Location)) { return this._Location_44; }
    if ((token === import26.UrlSerializer)) { return this._UrlSerializer_45; }
    if ((token === import27.RouterOutletMap)) { return this._RouterOutletMap_46; }
    if ((token === import53.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_47; }
    if ((token === import54.ROUTES)) { return this._ROUTES_48; }
    if ((token === import42.Router)) { return this._Router_49; }
    if ((token === import55.ActivatedRoute)) { return this._ActivatedRoute_50; }
    if ((token === import29.NoPreloading)) { return this._NoPreloading_51; }
    if ((token === import29.PreloadingStrategy)) { return this._PreloadingStrategy_52; }
    if ((token === import29.RouterPreloader)) { return this._RouterPreloader_53; }
    if ((token === import29.PreloadAllModules)) { return this._PreloadAllModules_54; }
    if ((token === import6.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_55; }
    if ((token === import33.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_56; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__15.ngOnDestroy();
    this._DomSharedStylesHost_23.ngOnDestroy();
    this._RouterPreloader_53.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);