/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './main.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/router/src/router_module';
import * as import4 from './main.routes';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from 'angular2-moment/moment.module';
import * as import8 from 'ngx-bootstrap/alert/alert.module';
import * as import9 from 'ngx-bootstrap/datepicker/datepicker.module';
import * as import10 from '@angular/common/src/localization';
import * as import11 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import12 from 'ngx-bootstrap/alert/alert.config';
import * as import13 from 'ngx-bootstrap/datepicker/datepicker.config';
import * as import14 from '@angular/core/src/di/injector';
import * as import15 from './main.component.ngfactory';
import * as import16 from '../../../node_modules/ngx-bootstrap/alert/alert.component.ngfactory';
import * as import17 from '../../../node_modules/ngx-bootstrap/datepicker/datepicker.component.ngfactory';
import * as import18 from '@angular/core/src/i18n/tokens';
import * as import19 from './main.component';
import * as import20 from '@angular/router/src/router_config_loader';
class MainModuleInjector extends import0.NgModuleInjector<import1.MainModule> {
  _CommonModule_0:import2.CommonModule;
  _RouterModule_1:import3.RouterModule;
  _MainRoutesModule_2:import4.MainRoutesModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _MomentModule_5:import7.MomentModule;
  _AlertModule_6:import8.AlertModule;
  _DatepickerModule_7:import9.DatepickerModule;
  _MainModule_8:import1.MainModule;
  __NgLocalization_9:import10.NgLocaleLocalization;
  __ROUTES_10:any[];
  __RadioControlRegistry_11:import11.RadioControlRegistry;
  __AlertConfig_12:import12.AlertConfig;
  __DatepickerConfig_13:import13.DatepickerConfig;
  constructor(parent:import14.Injector) {
    super(parent,[
      import15.MainComponentNgFactory,
      import16.AlertComponentNgFactory,
      import17.DatePickerComponentNgFactory
    ]
    ,[import15.MainComponentNgFactory]);
  }
  get _NgLocalization_9():import10.NgLocaleLocalization {
    if ((this.__NgLocalization_9 == null)) { (this.__NgLocalization_9 = new import10.NgLocaleLocalization(this.parent.get(import18.LOCALE_ID))); }
    return this.__NgLocalization_9;
  }
  get _ROUTES_10():any[] {
      if ((this.__ROUTES_10 == null)) { (this.__ROUTES_10 = [[
        {
          path: '',
          component: import19.MainComponent
        }
        ,
        {
          path: '**',
          redirectTo: '',
          pathMatch: 'full'
        }

      ]
    ]); }
    return this.__ROUTES_10;
  }
  get _RadioControlRegistry_11():import11.RadioControlRegistry {
    if ((this.__RadioControlRegistry_11 == null)) { (this.__RadioControlRegistry_11 = new import11.RadioControlRegistry()); }
    return this.__RadioControlRegistry_11;
  }
  get _AlertConfig_12():import12.AlertConfig {
    if ((this.__AlertConfig_12 == null)) { (this.__AlertConfig_12 = new import12.AlertConfig()); }
    return this.__AlertConfig_12;
  }
  get _DatepickerConfig_13():import13.DatepickerConfig {
    if ((this.__DatepickerConfig_13 == null)) { (this.__DatepickerConfig_13 = new import13.DatepickerConfig()); }
    return this.__DatepickerConfig_13;
  }
  createInternal():import1.MainModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._RouterModule_1 = new import3.RouterModule(this.parent.get(import3.ROUTER_FORROOT_GUARD,(null as any)));
    this._MainRoutesModule_2 = new import4.MainRoutesModule();
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._MomentModule_5 = new import7.MomentModule();
    this._AlertModule_6 = new import8.AlertModule();
    this._DatepickerModule_7 = new import9.DatepickerModule();
    this._MainModule_8 = new import1.MainModule();
    return this._MainModule_8;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.RouterModule)) { return this._RouterModule_1; }
    if ((token === import4.MainRoutesModule)) { return this._MainRoutesModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.MomentModule)) { return this._MomentModule_5; }
    if ((token === import8.AlertModule)) { return this._AlertModule_6; }
    if ((token === import9.DatepickerModule)) { return this._DatepickerModule_7; }
    if ((token === import1.MainModule)) { return this._MainModule_8; }
    if ((token === import10.NgLocalization)) { return this._NgLocalization_9; }
    if ((token === import20.ROUTES)) { return this._ROUTES_10; }
    if ((token === import11.RadioControlRegistry)) { return this._RadioControlRegistry_11; }
    if ((token === import12.AlertConfig)) { return this._AlertConfig_12; }
    if ((token === import13.DatepickerConfig)) { return this._DatepickerConfig_13; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const MainModuleNgFactory:import0.NgModuleFactory<import1.MainModule> = new import0.NgModuleFactory(MainModuleInjector,import1.MainModule);