/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './admin.routes';
import * as import2 from '@angular/router/src/router_module';
import * as import3 from '@angular/core/src/di/injector';
import * as import4 from './admin.component.ngfactory';
import * as import5 from './admin.component';
import * as import6 from '@angular/router/src/router_config_loader';
class AdminRoutesModuleInjector extends import0.NgModuleInjector<import1.AdminRoutesModule> {
  _RouterModule_0:import2.RouterModule;
  _AdminRoutesModule_1:import1.AdminRoutesModule;
  __ROUTES_2:any[];
  constructor(parent:import3.Injector) {
    super(parent,[import4.AdminComponentNgFactory],([] as any[]));
  }
  get _ROUTES_2():any[] {
      if ((this.__ROUTES_2 == null)) { (this.__ROUTES_2 = [[
        {
          path: '',
          component: import5.AdminComponent
        }
        ,
        {
          path: '**',
          redirectTo: '',
          pathMatch: 'full'
        }

      ]
    ]); }
    return this.__ROUTES_2;
  }
  createInternal():import1.AdminRoutesModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ROUTER_FORROOT_GUARD,(null as any)));
    this._AdminRoutesModule_1 = new import1.AdminRoutesModule();
    return this._AdminRoutesModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.AdminRoutesModule)) { return this._AdminRoutesModule_1; }
    if ((token === import6.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AdminRoutesModuleNgFactory:import0.NgModuleFactory<import1.AdminRoutesModule> = new import0.NgModuleFactory(AdminRoutesModuleInjector,import1.AdminRoutesModule);