/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './admin.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/router/src/router_module';
import * as import4 from './admin.routes';
import * as import5 from '@angular/common/src/localization';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from './admin.component.ngfactory';
import * as import8 from '@angular/core/src/i18n/tokens';
import * as import9 from './admin.component';
import * as import10 from '@angular/router/src/router_config_loader';
class AdminModuleInjector extends import0.NgModuleInjector<import1.AdminModule> {
  _CommonModule_0:import2.CommonModule;
  _RouterModule_1:import3.RouterModule;
  _AdminRoutesModule_2:import4.AdminRoutesModule;
  _AdminModule_3:import1.AdminModule;
  __NgLocalization_4:import5.NgLocaleLocalization;
  __ROUTES_5:any[];
  constructor(parent:import6.Injector) {
    super(parent,[import7.AdminComponentNgFactory],[import7.AdminComponentNgFactory]);
  }
  get _NgLocalization_4():import5.NgLocaleLocalization {
    if ((this.__NgLocalization_4 == null)) { (this.__NgLocalization_4 = new import5.NgLocaleLocalization(this.parent.get(import8.LOCALE_ID))); }
    return this.__NgLocalization_4;
  }
  get _ROUTES_5():any[] {
      if ((this.__ROUTES_5 == null)) { (this.__ROUTES_5 = [[
        {
          path: '',
          component: import9.AdminComponent
        }
        ,
        {
          path: '**',
          redirectTo: '',
          pathMatch: 'full'
        }

      ]
    ]); }
    return this.__ROUTES_5;
  }
  createInternal():import1.AdminModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._RouterModule_1 = new import3.RouterModule(this.parent.get(import3.ROUTER_FORROOT_GUARD,(null as any)));
    this._AdminRoutesModule_2 = new import4.AdminRoutesModule();
    this._AdminModule_3 = new import1.AdminModule();
    return this._AdminModule_3;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.RouterModule)) { return this._RouterModule_1; }
    if ((token === import4.AdminRoutesModule)) { return this._AdminRoutesModule_2; }
    if ((token === import1.AdminModule)) { return this._AdminModule_3; }
    if ((token === import5.NgLocalization)) { return this._NgLocalization_4; }
    if ((token === import10.ROUTES)) { return this._ROUTES_5; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AdminModuleNgFactory:import0.NgModuleFactory<import1.AdminModule> = new import0.NgModuleFactory(AdminModuleInjector,import1.AdminModule);